name: DVC CI
on:
  push:
    branches:
      - main  # Или ваша ветка продакшена
jobs:
  dvc-setup-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install DVC
        run: pip install dvc

      - name: Initialize DVC
        run: dvc init

      - name: Configure DVC Remote
        run: |
          dvc remote add -d myremote s3://my-dvc-backet
          dvc remote modify myremote access_key_id ${{ secrets.YANDEX_ACCESS_KEY_ID }}
          dvc remote modify myremote secret_access_key ${{ secrets.YANDEX_SECRET_ACCESS_KEY }}
          dvc remote modify myremote endpointurl https://storage.yandexcloud.net

      - name: DVC Pull Data
        run: dvc pull  # Скачиваем все зависимости

      - name: Run DVC Pipeline
        run: dvc repro  # Запускаем пайплайн

      - name: DVC Push Data
        run: dvc push  # Отправляем результаты

      - name: Git add and commit DVC files
        run: |
          git config user.email "github-actions@example.com"
          git config user.name "GitHub Actions"
          git add .dvc
          git commit -m "Update DVC data"

      - name: Git push DVC Config
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
